name: review

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repository
        uses: actions/checkout@v6

      - name: 🏗 Setup project
        uses: ./.github/actions/setup-project
        with:
          bun-version: latest

      - name: 📦 Install dependencies
        run: bun install

      - name: ✅ Lint code
        run: bun run lint --max-warnings=0

      - name: 🧪 Test code
        run: bun run test
